services:
  - type: web
    name: tic-tac-toe
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: tic-tac-toe-db
          property: connectionString

databases:
  - name: tic-tac-toe-db
    databaseName: tic_tac_toe
    user: tic_tac_toe_user 